import { pool } from '../db/connection';
import type { FoodEntry, MealType, Micronutrients } from '../types';
import type { PageQuery } from '../utils/pagination';

export interface MealInput {
  mealType: MealType;
  foodName: string;
  quantity: number;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number;
  vitamins: Micronutrients;
  minerals: Micronutrients;
  consumedAt: string;
  /** Marks entries generated by the demo-data seeder (so they can be reset). */
  isSeeded?: boolean;
}

export interface MealFilters {
  start?: string;
  end?: string;
  mealType?: MealType;
}

interface MealDbRow {
  id: number;
  user_id: number;
  meal_type: MealType;
  food_name: string;
  quantity: number;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number;
  vitamins: unknown;
  minerals: unknown;
  consumed_at: Date;
  created_at: Date;
}

function parseMicros(value: unknown): Micronutrients {
  if (value == null) return {};
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      return parsed && typeof parsed === 'object' ? parsed : {};
    } catch {
      return {};
    }
  }
  if (typeof value === 'object') return value as Micronutrients;
  return {};
}

function mapRow(row: MealDbRow): FoodEntry {
  return {
    id: row.id,
    userId: row.user_id,
    mealType: row.meal_type,
    foodName: row.food_name,
    quantity: row.quantity,
    unit: row.unit,
    calories: row.calories,
    protein: row.protein,
    carbs: row.carbs,
    fat: row.fat,
    fiber: row.fiber,
    sugar: row.sugar,
    sodium: row.sodium,
    vitamins: parseMicros(row.vitamins),
    minerals: parseMicros(row.minerals),
    consumedAt: row.consumed_at.toISOString(),
    createdAt: row.created_at.toISOString(),
  };
}

const MEAL_COLUMNS = `id, user_id, meal_type, food_name, quantity, unit, calories,
  protein, carbs, fat, fiber, sugar, sodium, vitamins, minerals, consumed_at, created_at`;

const DATE_RANGE = `(consumed_at AT TIME ZONE 'Asia/Kolkata')::date`;

export async function createMeal(userId: number, input: MealInput): Promise<FoodEntry> {
  const { rows } = await pool.query<MealDbRow>(
    `INSERT INTO food_entries
       (user_id, meal_type, food_name, quantity, unit, calories, protein, carbs,
        fat, fiber, sugar, sodium, vitamins, minerals, consumed_at, is_seeded)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
     RETURNING ${MEAL_COLUMNS}`,
    [
      userId, input.mealType, input.foodName, input.quantity, input.unit,
      input.calories, input.protein, input.carbs, input.fat, input.fiber,
      input.sugar, input.sodium,
      JSON.stringify(input.vitamins ?? {}), JSON.stringify(input.minerals ?? {}),
      input.consumedAt,
      input.isSeeded ?? false,
    ],
  );
  return mapRow(rows[0]);
}

export async function getMealById(id: number, userId: number): Promise<FoodEntry | undefined> {
  const { rows } = await pool.query<MealDbRow>(
    `SELECT ${MEAL_COLUMNS} FROM food_entries WHERE id = $1 AND user_id = $2`,
    [id, userId],
  );
  return rows[0] ? mapRow(rows[0]) : undefined;
}

export interface MealListResult {
  entries: FoodEntry[];
  total: number;
}

export async function listMeals(
  userId: number,
  filters: MealFilters,
  page: PageQuery,
): Promise<MealListResult> {
  const conditions = ['user_id = $1'];
  const params: unknown[] = [userId];

  if (filters.start) {
    params.push(filters.start);
    conditions.push(`${DATE_RANGE} >= $${params.length}`);
  }
  if (filters.end) {
    params.push(filters.end);
    conditions.push(`${DATE_RANGE} <= $${params.length}`);
  }
  if (filters.mealType) {
    params.push(filters.mealType);
    conditions.push(`meal_type = $${params.length}`);
  }

  const where = conditions.join(' AND ');

  const { rows: countRows } = await pool.query<{ count: number }>(
    `SELECT COUNT(*)::int AS count FROM food_entries WHERE ${where}`,
    params,
  );
  const total = countRows[0].count;

  params.push(page.pageSize, page.offset);
  const limitParam = params.length - 1;
  const offsetParam = params.length;

  const { rows } = await pool.query<MealDbRow>(
    `SELECT ${MEAL_COLUMNS} FROM food_entries WHERE ${where}
     ORDER BY consumed_at DESC, id DESC
     LIMIT $${limitParam} OFFSET $${offsetParam}`,
    params,
  );

  return { entries: rows.map(mapRow), total };
}

export async function updateMeal(id: number, userId: number, input: MealInput): Promise<FoodEntry | undefined> {
  const { rows } = await pool.query<MealDbRow>(
    `UPDATE food_entries SET
       meal_type = $1, food_name = $2, quantity = $3, unit = $4, calories = $5,
       protein = $6, carbs = $7, fat = $8, fiber = $9, sugar = $10, sodium = $11,
       vitamins = $12, minerals = $13, consumed_at = $14
     WHERE id = $15 AND user_id = $16
     RETURNING ${MEAL_COLUMNS}`,
    [
      input.mealType, input.foodName, input.quantity, input.unit, input.calories,
      input.protein, input.carbs, input.fat, input.fiber, input.sugar, input.sodium,
      JSON.stringify(input.vitamins ?? {}), JSON.stringify(input.minerals ?? {}),
      input.consumedAt, id, userId,
    ],
  );
  return rows[0] ? mapRow(rows[0]) : undefined;
}

export async function deleteMeal(id: number, userId: number): Promise<boolean> {
  const result = await pool.query(
    'DELETE FROM food_entries WHERE id = $1 AND user_id = $2',
    [id, userId],
  );
  return (result.rowCount ?? 0) > 0;
}

/** Delete every food entry for a user. Returns the number of rows removed. */
export async function deleteAllMeals(userId: number): Promise<number> {
  const result = await pool.query(
    'DELETE FROM food_entries WHERE user_id = $1',
    [userId],
  );
  return result.rowCount ?? 0;
}

/** Delete only seeded (demo) food entries for a user. */
export async function deleteSeededMeals(userId: number): Promise<number> {
  const result = await pool.query(
    'DELETE FROM food_entries WHERE user_id = $1 AND is_seeded = true',
    [userId],
  );
  return result.rowCount ?? 0;
}

export interface DailyTotalsRow {
  date: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number;
}

/** Aggregated nutrition totals per calendar day in India Standard Time. */
export async function getDailyTotals(userId: number, start: string, end: string): Promise<DailyTotalsRow[]> {
  const { rows } = await pool.query<DailyTotalsRow>(
    `SELECT to_char(consumed_at AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM-DD') AS date,
            COALESCE(SUM(calories), 0) AS calories,
            COALESCE(SUM(protein), 0) AS protein,
            COALESCE(SUM(carbs), 0) AS carbs,
            COALESCE(SUM(fat), 0) AS fat,
            COALESCE(SUM(fiber), 0) AS fiber,
            COALESCE(SUM(sugar), 0) AS sugar,
            COALESCE(SUM(sodium), 0) AS sodium
     FROM food_entries
     WHERE user_id = $1 AND ${DATE_RANGE} >= $2 AND ${DATE_RANGE} <= $3
     GROUP BY 1
     ORDER BY 1`,
    [userId, start, end],
  );
  return rows;
}

export interface MacroTotalsRow {
  protein: number;
  carbs: number;
  fat: number;
  calories: number;
}

export async function getMacroTotals(userId: number, start: string, end: string): Promise<MacroTotalsRow> {
  const { rows } = await pool.query<MacroTotalsRow>(
    `SELECT COALESCE(SUM(protein), 0) AS protein,
            COALESCE(SUM(carbs), 0) AS carbs,
            COALESCE(SUM(fat), 0) AS fat,
            COALESCE(SUM(calories), 0) AS calories
     FROM food_entries
     WHERE user_id = $1 AND ${DATE_RANGE} >= $2 AND ${DATE_RANGE} <= $3`,
    [userId, start, end],
  );
  return rows[0] ?? { protein: 0, carbs: 0, fat: 0, calories: 0 };
}

/** Raw vitamin/mineral maps for a date range, merged in memory. */
export async function getMicros(
  userId: number,
  start: string,
  end: string,
): Promise<{ vitamins: Micronutrients; minerals: Micronutrients }[]> {
  const { rows } = await pool.query<{ vitamins: unknown; minerals: unknown }>(
    `SELECT vitamins, minerals FROM food_entries
     WHERE user_id = $1 AND ${DATE_RANGE} >= $2 AND ${DATE_RANGE} <= $3`,
    [userId, start, end],
  );
  return rows.map((r) => ({ vitamins: parseMicros(r.vitamins), minerals: parseMicros(r.minerals) }));
}
